---
- name: Install nginx with vhosts
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: false

  vars:
    sites:
      - "yellowbear.org"
      - "savethemoon.net"
      - "worlddomination.com"

  roles:
    - nginx-vhosts
